export const HEALTH_SEQUELIZE_PROVIDER = Symbol('HEALTH_SEQUELIZE_PROVIDER');

export const HEALTH_DRIZZLE_PROVIDER = Symbol('HEALTH_DRIZZLE_PROVIDER');

export const HEALTH_MIKROORM_PROVIDER = Symbol('HEALTH_MIKROORM_PROVIDER');

export const HEALTH_PRISMA_PROVIDER = Symbol('HEALTH_PRISMA_PROVIDER');

export const HEALTH_TYPEORM_PROVIDER = Symbol('HEALTH_TYPEORM_PROVIDER');

export const HEALTH_MONGOOSE_PROVIDER = Symbol('HEALTH_MONGOOSE_PROVIDER');

export const HEALTH_POSTGRES_PROVIDER = Symbol('HEALTH_POSTGRES_PROVIDER');

export const HEALTH_MYSQL_PROVIDER = Symbol('HEALTH_MYSQL_PROVIDER');
