export const SEQUELIZE_PROVIDER_TOKEN = Symbol('SEQUELIZE_PROVIDER_TOKEN');

export const DRIZZLE_PROVIDER_TOKEN = Symbol('DRIZZLE_PROVIDER_TOKEN');

export const MIKRO_ORM_PROVIDER_TOKEN = Symbol('MIKRO_ORM_PROVIDER_TOKEN');

export const PRISMA_PROVIDER_TOKEN = Symbol('PRISMA_PROVIDER_TOKEN');

export const TYPEORM_PROVIDER_TOKEN = Symbol('TYPEORM_PROVIDER_TOKEN');

export const MONGOOSE_PROVIDER_TOKEN = Symbol('MONGOOSE_PROVIDER_TOKEN');

export const POSTGRES_PROVIDER_TOKEN = Symbol('POSTGRES_PROVIDER_TOKEN');

export const MYSQL_PROVIDER_TOKEN = Symbol('MYSQL_PROVIDER_TOKEN');
