export const CATCH_HTTP_EXCEPTION_FILTER_CONFIG = Symbol(
  'CATCH_HTTP_EXCEPTION_FILTER_CONFIG',
);

export const CATCH_EVERYTHING_FILTER_CONFIG = Symbol(
  'CATCH_EVERYTHING_FILTER_CONFIG',
);
